### ISSUE TITLE
gradle 编译报错 4.6版本的。 

### ISSUE THREAD

**Issue by 46602907** [heyuxian/mcloud#43]
jwqdeMacBook-Pro:mcloud jwq$ ./gradlew build -x test

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mcloud-console:bootJar'.
> The value of a manifest attribute must not be null (Key=Start-Class).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
11 actionable tasks: 2 executed, 9 up-to-date

**Comment by heyuxian** [comment]
已修改，请更新代码。
